Переименовал файлы. Поправил соответственно код.
fedorovregru/test_TTX_Moose pull request #1
Opened 2017-02-22 05:41 UTC by fedorovregru

2017-02-22 12:17 UTC, timurn commented on Vehicle.pm
> +    $self->SUPER::DEMOLISH;
Не надо путать уничтожение сущности, описываемой объектом, и уничтожение объекта. Если танк подбили, он всё ещё может оставаться на поле боя в нашей модели. К тому же, вроде бы, явный вызов DEMOLISH гайдами Moose не рекомендуется.

2017-02-26 15:49 UTC, timurn requested changes

2017-02-26 15:49 UTC, timurn commented on Weapon_machinegun.pm
> +	$self->bullets_counter( $self->magazine );
То, что у пулемёта есть магазин, не отменяет того, что у него ограниченный боезапас, уменьшающийся при перезарядке.

2017-02-26 15:49 UTC, timurn commented on Weapon_machinegun.pm
> +has 'magazine'         => ( is => 'ro', isa => 'Num' );
magazine_size скорее.

2017-02-26 15:49 UTC, timurn commented on Weapon_machinegun.pm
> +	$self->bullets_counter( $self->magazine );
А, ammo_count у тебя выполняется в shot. Вопрос снят тогда.

2017-02-26 15:49 UTC, timurn commented on Weapon_machinegun.pm
> +	$self->bullets_counter( $self->magazine );
Хотя всё же логичнее, наверное, было бы делать это в reload.

2017-02-26 15:49 UTC, timurn commented on Weapon_rocket.pm
> +extends 'Weapon';
Сможет ли ракета выстрелить хотя бы один раз?

2017-02-26 15:49 UTC, timurn commented on Vehicle.pm
> -__PACKAGE__->meta->make_immutable;
А почему убрал make_immutable, и зачем тут return 1?

2017-02-26 15:49 UTC, timurn commented on Vehicle/Artillery.pm
> +sub go_to_arty_position {
Нужно аккуратно относиться к именования. Здесь либо ты вообще убираешь arty, оставляешь go_to_position (или take_position, или into_position), потому что это метод, и если метод вызывается у артиллерии, то в общем и целом понятно, что она выходит на позицию артиллерии, а не на позицию корабля, например. Либо ты честно и ответственно пишешь go_to_artillery_position и не экономишь чернила и энергию своих пальцев.

2017-02-26 15:49 UTC, timurn commented on Vehicle/Tank.pm
> +    print 'Танки не летают и не плавают!';
Суть задачи была сделать так, чтобы если танк поплыл, то он утонул, если полетел, то разбился и т. п. Сейчас ты это вызываешь *до* метода fly/sail и выдаёшь предупреждение, тогда непонятно, чего, собственно, техника уничтожилась, если она никуда ещё не поплыла и не полетела.

2017-02-26 15:49 UTC, timurn commented on Vehicle.pm
Пустая строка здесь не нужна. К тому же, получение параметров должно быть максимально близко к объявлению функции, поскольку, условно, это часть сигнатуры.

2017-02-26 15:49 UTC, timurn commented on Vehicle.pm
> +    print 'уничтожен';
Давай договоримся для всех процедур (т. е. функций, выполняемых ради побочного эффекта): если выполнилась успешно — возвращает 1, если нет — либо выбрасывает исключение, либо возвращает 0.

2017-02-26 15:49 UTC, timurn commented on Vehicle.pm
> +    print 'уничтожен';
Ну и если вызывает другую функцию (как get_damage вызывает destroy), то либо проверяет, что она вернула, либо напрямую возвращает её результат.

2017-02-26 15:49 UTC, timurn commented on Vehicle/Ship.pm
> +    handles => { cannon_fire => 'shot' }
«Пушка выстрелить». Метод должен называться от глагола, «выстрелить из пушки», т. е. «fire_cannon». С торпедой же всё нормально сделано.

2017-02-26 15:49 UTC, timurn commented on Vehicle/Avia.pm
> +	handles => { mg_fire => 'shot' }
Выстрелить из магния? Или из миллиграмма?

2017-02-26 15:49 UTC, timurn commented on Vehicle/Artillery.pm
> +    handles => { fire => 'shot' }
По-хорошему, метод выстрела из пушки должен во всех классах называться одинаково. Полиморфизм, вот это всё.

2017-02-26 15:49 UTC, timurn commented on Vehicle/Artillery.pm
> +after 'get_damage' => sub {
А если внутри get_damage техника уже уничтожена, будет ли вызван этот метод?

2017-02-26 15:49 UTC, timurn commented on Vehicle/Artillery.pm
> +    if ( int( rand(100) ) < 11 ) {
Во-первых, вообще говоря, этот блок кода везде одинаков,  за исключением строки в print. Желательно общий код вынести в общий метод, а в самих модулях специфицировать  только то, что нужно.

Во-вторых, подрыв боекомплекта, наверное, лучше сделать методом.

В-третьих, хардкодить цифры, тем более в нескольких местах — зло.

С учётом всего этого нужно привести в порядок это место.

2017-02-26 15:49 UTC, timurn commented on Weapon.pm
> +	die 'выстрел без боеприпаса!' if $self->ammo_count < 1;
Ну, вообще говоря, попытка выстрелить из незаряженного орудия — это нормальный случай в предметной области, а не ошибка в программе. Поэтому обрабатывать её нужно более мягко.

2017-02-26 15:49 UTC, timurn commented on Weapon/Machinegun.pm
> +    $self->reload if $self->bullets_counter == 0;
Почему сначала проверяется bullets_counter, а только потом декрементится?

2017-02-26 15:49 UTC, timurn commented on Weapon.pm
> +sub shot {
Надо как-то всё-таки дотюнить логику выстрела и перезарядки. Есть боезапас и его размер. Есть орудие и его ёмкость/размер магазина. При перезарядке снаряды берутся из боезапаса и заряжаются в орудие. Если перезаряжать нечем, то стрельба заканчивается. При выстреле снаряды выстреливаются из орудия, и, если их там не осталось, происходит перезарядка. Если орудие пустое и перезаряжать нечем, то выстрела не происходит.

2017-02-26 15:49 UTC, timurn commented on Weapon.pm
> +sub shot {
Ну и, кстати, наверное, нужно заряжать орудие при создании объекта.

2017-02-26 17:07 UTC, fedorovregru commented on Vehicle.pm
> +    print 'уничтожен';
хорошо, поправил

2017-02-26 17:09 UTC, fedorovregru commented on Vehicle.pm
поправил

2017-02-26 17:10 UTC, fedorovregru commented on Vehicle.pm
> -__PACKAGE__->meta->make_immutable;
посчитал лишним, вернул назад

2017-02-26 17:14 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +    handles => { fire => 'shot' }
Изменил на cannon_fire

2017-02-26 17:22 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +after 'get_damage' => sub {
Да, будет. Сделал просчет критического урона перед get_damage. Плюс вместо вызова $self->destroy теперь просто обнуляется $self->durability.

2017-02-26 17:29 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +    if ( int( rand(100) ) < 11 ) {
вынес код просчета критического попадания в общий метод, ввел переменную $critical_damage_chance

2017-02-26 17:31 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +sub go_to_arty_position {
Переименовал в go_to_artillery_position

2017-02-26 17:35 UTC, fedorovregru commented on Vehicle/Tank.pm
> +    print 'Танки не летают и не плавают!';
Понял, действительно нелогично. Исправил на after

2017-02-26 17:37 UTC, fedorovregru commented on Vehicle/Ship.pm
> +    handles => { cannon_fire => 'shot' }
переименовал

2017-02-26 17:37 UTC, fedorovregru commented on Vehicle/Avia.pm
> +	handles => { mg_fire => 'shot' }
написал полностью

2017-02-26 17:43 UTC, fedorovregru commented on Weapon.pm
> +	die 'выстрел без боеприпаса!' if $self->ammo_count < 1;
сделал выход из функции с ошибкой return 0;

2017-02-26 19:39 UTC, fedorovregru commented on Weapon.pm
> +sub shot {
Логику переделал

2017-02-27 06:35 UTC, timurn commented on Vehicle.pm
> +my $critical_damage_chance = 10;
Лучше (тем более, раз мы  тут  занимаемся ООП) не заводить переменные на внешнем уровне, а возвращать всё из методов, либо делаь полем объекта. Даже если это константа.

2017-02-27 06:37 UTC, timurn commented on Vehicle.pm
> +    return $self->destroy if $self->durability <= 0;
Два return подряд не очень красиво, лучше использовать тернарный условный оператор:

```perl
return $self->durability <= 0 ? $self->destroy : 1
```

2017-02-27 06:40 UTC, timurn commented on Vehicle.pm
> +    return 1 if int( rand(100) ) <= $critical_damage_chance;
Тут, опять же, два return некрасиво. Достаточно вернуть результат сравнения.

2017-02-27 06:42 UTC, timurn commented on Vehicle/Artillery.pm
> +after 'new' => sub {
Наверное, https://metacpan.org/pod/distribution/Moose/lib/Moose/Manual/Construction.pod#BUILD.

2017-02-27 06:43 UTC, timurn commented on Vehicle/Artillery.pm
> +before 'get_damage' => sub {
Не, ну сначала ты получил снарядом, а уже потом, может быть, у тебя ещё и что-то взорвалось.

2017-02-27 06:44 UTC, timurn commented on Vehicle/Artillery.pm
> +before 'get_damage' => sub {
Ну и, соответственно, нужно будет явно уничтожаться, а не надеяться на `get_damage`.

2017-02-27 06:45 UTC, timurn commented on Vehicle/Artillery.pm
> +after [qw( fly sail )] => sub {
Давай сделаем честно и красиво: after sail print утонул, destroy, и т. д.

2017-02-27 06:46 UTC, timurn commented on Vehicle/Artillery.pm
> +after 'new' => sub {
Может, из-за этого и ворнинги про конструктор у тебя были.

2017-02-27 06:49 UTC, timurn commented on Weapon.pm
> +
Тут тогда уж должно быть `print 'выстрелил'`.

2017-02-27 06:50 UTC, timurn commented on Weapon/Cannon.pm
> +has 'magazine_size' => (
Раз уж ты сделал роль Reloadable, то ничто не мешает и поля `magazine_size/magazine_ammo` вынести в неё.

2017-02-27 06:52 UTC, timurn commented on Weapon/Cannon.pm
> +        print 'кончился боезапас!' unless $self->reload;
Что кончился боезапас логично сообщать в `reload`, а тут как раз нужно выйти с правильным статусом.

2017-02-27 06:53 UTC, timurn commented on Weapon/Cannon.pm
> +sub BUILD {
Опять же, это в роль надо вынести, наверное.

2017-02-27 06:55 UTC, timurn commented on Weapon/Cannon.pm
> +    if ( $self->magazine_ammo == 0 ) {
Да и это всё в роль. shot должен быть стандартный в родительском классе, который говорит "выстрелил".

2017-02-27 06:57 UTC, fedorovregru commented on Vehicle.pm
> +my $critical_damage_chance = 10;
Сделал полем класса со значением по-умолчанию 10

2017-02-27 06:59 UTC, fedorovregru commented on Vehicle.pm
> +    return $self->destroy if $self->durability <= 0;
Сделал через тернарный оператор сравнения

2017-02-27 06:59 UTC, fedorovregru commented on Vehicle.pm
> +    return 1 if int( rand(100) ) <= $critical_damage_chance;
окей, исправил

2017-02-27 07:00 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +after 'new' => sub {
Ага, уже поправил

2017-02-27 07:13 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +after [qw( fly sail )] => sub {
Сделал честно, отдельные методы.

2017-02-27 07:14 UTC, fedorovregru commented on Vehicle/Artillery.pm
> +before 'get_damage' => sub {
исправил

2017-02-27 07:15 UTC, fedorovregru commented on Weapon.pm
> +
добавил print

2017-02-27 07:21 UTC, fedorovregru commented on Weapon/Cannon.pm
> +has 'magazine_size' => (
вынес поля в роль Reloadable

2017-02-27 07:31 UTC, fedorovregru commented on Weapon/Cannon.pm
> +        print 'кончился боезапас!' unless $self->reload;
Убрал сообщение в метод reload. сделал выход со статусом return 1 или 0 через тернарный оператор.

2017-02-27 07:32 UTC, fedorovregru commented on Weapon/Cannon.pm
> +sub BUILD {
Вынес в роль, работает.

2017-02-27 07:47 UTC, fedorovregru commented on Weapon/Cannon.pm
> +    if ( $self->magazine_ammo == 0 ) {
Убрал в роль.

2017-03-02 16:40 UTC, merged